### ISSUE TITLE
US#10-Create Parent log-in

### ISSUE THREAD

**Issue by ire-mar** [theraf01/Tech-Army#12]
As a parent, I want to have a log-in page, so that I can view my registered details in the system.

**Comment by theraf01** [comment]
[US10-Wireframe and AC.docx](https://github.com/theraf01/Tech-Army/files/4580461/US10-Wireframe.and.AC.docx)
Acceptance Criteria: for US#10 - 10. As a parent, I want to have a log-in page, so that I can view my registered details in the system
	The parent should be able to enter the user name
	The parent should be able to enter the password
	The parent should be able to login by clicking the login button 
	The parent should be able to click on the forgot password link
	The parent should be able to go to parent page by clicking valid username and password.
	The parent should not be able go to parent page by clicking in-valid username and password.
	The parent should not be able go to parent page by clicking valid username and invalid password.
	The parent should not be able go to parent page by clicking in-valid username and valid password.
	The parent should be able to view their registered details in the profile page.
	The parent should not be able to view other’s registered details on the profile page.

**Comment by ire-mar** [comment]
- [x] Text Input for Username and password
- [x] Login Button
